javascript:
  libs:
    require:
      - react
      - react-bootstrap
      - react-dom
      - react-redux
      - react-router
      - react-router-redux
      - redux
      - redux-thunk
  application:
    external:
      - react
      - react-bootstrap
      - react-dom
      - react-redux
      - react-router
      - react-router-redux
      - redux
      - redux-thunk
